### ISSUE TITLE
Error 404's

### ISSUE THREAD

**Issue by crackulator** [Havard03/spotr#21]
I have installed the app and gone through the authentication process... that part seemed to work, didn't report any errors. It seems to have access to my account, as when I do "playlist" it reports my playlists and lets me choose one before erroring out. But nothing seems to work, it reports 404 or 400 errors.

Here is a debug run where I selected a playlist:
```
bob@punq:~$ .local/bin/spotr -d playlist
[23:10:19] DEBUG    Namespace(debug=True, current=False, command='playlist')                                                                                                                                                    parser.py:25
           DEBUG    Executing [<class 'spotrpy.controllers.playlistController.playlistController'>, 'run']                                                                                                                      parser.py:63
           DEBUG    BaseController initialized Logging                                                                                                                                                                  BaseController.py:16
           DEBUG    BaseController initialized Config                                                                                                                                                                   BaseController.py:19
           DEBUG    BaseController initialized API                                                                                                                                                                      BaseController.py:22
           DEBUG    Starting new HTTPS connection (1): api.spotify.com:443                                                                                                                                             connectionpool.py:978
           DEBUG    https://api.spotify.com:443 "GET /v1/me/playlists?limit=50 HTTP/1.1" 200 None                                                                                                                      connectionpool.py:453
           DEBUG    Using selector: EpollSelector                                                                                                                                                                      selector_events.py:54
[23:10:37] DEBUG    Starting new HTTPS connection (1): api.spotify.com:443                                                                                                                                             connectionpool.py:978
[23:10:38] DEBUG    https://api.spotify.com:443 "PUT /v1/me/player/play HTTP/1.1" 404 None                                                                                                                             connectionpool.py:453
           ERROR    Requst error - 404                                                                                                                                                                                             API.py:35
```
... and one attempting a search:
```
bob@punq:~$ .local/bin/spotr -d search
[23:11:31] DEBUG    Namespace(debug=True, current=False, command='search', query=[], type=None)                                                                                                                                 parser.py:25
           DEBUG    Executing [<class 'spotrpy.controllers.searchController.searchController'>, 'run']                                                                                                                          parser.py:63
           DEBUG    BaseController initialized Logging                                                                                                                                                                  BaseController.py:16
           DEBUG    BaseController initialized Config                                                                                                                                                                   BaseController.py:19
           DEBUG    BaseController initialized API                                                                                                                                                                      BaseController.py:22
           DEBUG    Using selector: EpollSelector                                                                                                                                                                      selector_events.py:54
[23:11:44] DEBUG    Starting new HTTPS connection (1): api.spotify.com:443                                                                                                                                             connectionpool.py:978
           DEBUG    https://api.spotify.com:443 "GET /v1/search?q=&type=track&limit=36 HTTP/1.1" 400 None                                                                                                              connectionpool.py:453
           ERROR    Requst error - 400                                                                                                                                                                                             API.py:35
           DEBUG    Refreshing API-Token                                                                                                                                                                                           API.py:53
           DEBUG    Starting new HTTPS connection (1): accounts.spotify.com:443                                                                                                                                        connectionpool.py:978
[23:11:45] DEBUG    https://accounts.spotify.com:443 "POST /api/token HTTP/1.1" 200 None                                                                                                                               connectionpool.py:453
           DEBUG    Starting new HTTPS connection (1): api.spotify.com:443                                                                                                                                             connectionpool.py:978
           DEBUG    https://api.spotify.com:443 "GET /v1/search?q=&type=track&limit=36 HTTP/1.1" 400 None                                                                                                              connectionpool.py:453
Traceback (most recent call last):
  File "/home/fritz/.local/bin/spotr", line 8, in <module>
    sys.exit(main())
  File "/home/fritz/.local/lib/python3.10/site-packages/spotrpy/main.py", line 4, in main
    Parser()
  File "/home/fritz/.local/lib/python3.10/site-packages/spotrpy/parser/parser.py", line 27, in __init__
    self.exec()
  File "/home/fritz/.local/lib/python3.10/site-packages/spotrpy/parser/parser.py", line 69, in exec
    getattr(controller, callable[1])()
  File "/home/fritz/.local/lib/python3.10/site-packages/spotrpy/controllers/searchController.py", line 61, in run
    choices = self.parse_items(
  File "/home/fritz/.local/lib/python3.10/site-packages/spotrpy/util/Helpers.py", line 28, in parse_items
    for item in (self.__get_item(data, accessor) if accessor else data)
  File "/home/fritz/.local/lib/python3.10/site-packages/spotrpy/util/Helpers.py", line 8, in __get_item
    data = data[key]
KeyError: 'tracks'

```
Any idea what is going wrong here?

**Comment by crackulator** [comment]
Perhaps you're having the same problem spotify-player is having? Seems like spotify changed their authentication API...

https://github.com/aome510/spotify-player/issues/520

**Comment by Havard03** [comment]
Hey, Ty for the info. I will look into this in the weekend 😁

**Comment by Havard03** [comment]
@crackulator I looked into this and was not able to recreate the issue. Do you have a premium / paid spotify account? as this is required for the API service.

I have made a new flag "-r" to dump the response for the api, this might display an error message that will help you identify the issue. Pull down the new changes and try another run with this flag.

This could also have been a temporary issue with the API service. Have you tested it again recently? Also might help to do the auth process again as i tried it today and everything worked fine.

**Comment by crackulator** [comment]
Yes I have a premium account. Is the "code" that you're supposed to clip from the URL normally 446 characters long?
I'll try the -r flag when I have a few minutes...

**Comment by Havard03** [comment]
Yes the key / code is very long
